# Fabric Properties
minecraft_version=26.1
curseforge_minecraft_versions=26.1
modrinth_minecraft_versions=26.1
java_version=25
# Dependencies
fabric_version=0.144.0+26.1
permission_api_version=0.7.0
placeholder_api_version=3.0.0-beta.2+26.1
player_data_api_version=0.10.0+26.1
server_translations_api_version=3.0.3+26.1
vanish_version=1.6.6+26.1
