# Fabric Properties
minecraft_version=1.21.11
curseforge_minecraft_versions=1.21.11
modrinth_minecraft_versions=1.21.11
java_version=21
# Dependencies
fabric_version=0.139.5+1.21.11
permission_api_version=0.6.0-patbox
placeholder_api_version=2.8.1+1.21.10
player_data_api_version=0.9.1+1.21.11
server_translations_api_version=2.5.2+1.21.9-pre3
vanish_version=1.6.2+1.21.11-rc2
