# Fabric Properties
minecraft_version=26.3
curseforge_minecraft_versions=26.3
modrinth_minecraft_versions=26.3
java_version=25
# Dependencies
fabric_version=0.161.0+26.3
permission_api_version=0.7.0
placeholder_api_version=3.2.0+26.3
player_data_api_version=0.11.0+26.2
server_translations_api_version=3.2.0+26.3
vanish_version=1.6.15+26.2
